"""The demo page, checked against the code it claims to be showing.

`ui/index.html` is the one artefact in this project written for a reader who will not read the
source: press a button, watch the pipeline answer. That makes it the easiest place in the repo
for a comfortable lie to live — a hand-typed verdict table, a reason code that no longer exists,
a copy of a response that stopped being true when the gate changed. None of that would fail any
other test, because nothing else in the suite looks at the page.

So these tests treat the page as a claim about the pipeline and check it the way any other claim
is checked. The page's two machine-readable blocks are the ones that matter:

* ``#recorded-runs`` — generated by ``scripts/build_ui_demo.py`` from a real offline run. Asserted
  here to still match a fresh run, which is what makes it a fallback rather than a second source
  of truth. It is also asserted PHI-free: it is machine-generated, it is embedded in a file anyone
  can open, and its whole justification is that it holds only what may cross.
* ``#demo-copy`` — hand-written, and the only prose on the page not derived from the pipeline. It
  is allowed to name things in words; it is not allowed to name things that do not exist, so its
  keys are checked against the fixture set and the hold codes.

Two fields genuinely cannot match between runs, and the comparison is built around them rather
than around them being absent. ``eta`` is wall-clock at minute resolution. Each audit event's
``hash`` covers a ``recorded`` timestamp taken at second resolution, so the digests differ every
second and the chain is supposed to look different each time. Both are asserted to be present and
well-formed; only their values are excluded.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient

from app.config import Settings
from app.hl7 import fixtures
from app.main import Service, create_app
from app.models import ALERT_FIELDS, HoldCode
from tests.conftest import RECORDED_RXNAV, RecordedRxNavTransport, TEST_SETTINGS
from tests.test_api import assert_no_phi

UI = Path(__file__).resolve().parents[1] / "ui" / "index.html"


def block(block_id: str) -> Any:
    """The JSON out of one ``<script type="application/json" id="...">`` on the page."""
    match = re.search(
        rf'<script type="application/json" id="{re.escape(block_id)}">(.*?)</script>',
        UI.read_text(),
        re.DOTALL,
    )
    assert match is not None, f"the page has no #{block_id} block"
    return json.loads(match.group(1))


@pytest.fixture(scope="module")
def page() -> str:
    return UI.read_text()


@pytest.fixture(scope="module")
def recorded() -> dict[str, Any]:
    return block("recorded-runs")


@pytest.fixture(scope="module")
def copy() -> dict[str, Any]:
    return block("demo-copy")


@pytest.fixture(scope="module")
def fresh() -> dict[str, Any]:
    """Every fixture, run through the pipeline offline, right now.

    Both this and the recorded block come from a *dry-run* service, so the comparison is
    between two runs of the same code over the same in-memory FHIR dataset. Module-scoped
    because it is only ever compared against, never mutated.
    """
    settings = Settings(**{**TEST_SETTINGS.model_dump(), "fhir_mode": "dry-run"})
    recorded_rxnav = json.loads(RECORDED_RXNAV.read_text())

    def factory() -> Service:
        return Service(settings, rxnav_transport=RecordedRxNavTransport(recorded_rxnav))

    runs: dict[str, Any] = {}
    with TestClient(create_app(factory)) as client:
        for name in sorted(fixtures.FIXTURES):
            response = client.post(f"/indent/demo/{name}")
            assert response.status_code == 200, f"{name} answered {response.status_code}"
            runs[name] = response.json()
    return runs


def stable(run: dict[str, Any]) -> dict[str, Any]:
    """A run with the clock taken out — the part that has to match between any two runs.

    Dropping a field entirely would let a real regression hide behind the exclusion, so the
    volatile ones are removed by name and separately asserted to be well-formed by
    :func:`test_the_volatile_fields_are_still_there`.
    """
    view = {key: value for key, value in run.items() if key != "eta"}
    if "alert" in view:
        view["alert"] = {k: v for k, v in view["alert"].items() if k != "eta"}
    view["audit"] = [
        {k: v for k, v in event.items() if k not in {"hash", "prev_hash"}}
        for event in view.get("audit", [])
    ]
    return view


# -- the generated block ----------------------------------------------------------------


def test_the_recorded_runs_cover_every_fixture(recorded: dict[str, Any]) -> None:
    """A new fixture with no recording is a button that would have nothing to show."""
    assert set(recorded["runs"]) == set(fixtures.FIXTURES)


def test_the_recorded_runs_match_a_real_pipeline_run(
    recorded: dict[str, Any], fresh: dict[str, Any]
) -> None:
    """The fallback is only honest if it is what the pipeline actually does.

    This is the test that lets the page embed results at all. Without it it would be a second
    source of truth, and the first gate that changed would make it a liar.
    """
    for name in sorted(fresh):
        assert stable(recorded["runs"][name]) == stable(fresh[name]), (
            f"the recorded run for {name!r} no longer matches the pipeline — "
            "re-run scripts/build_ui_demo.py"
        )


def test_the_volatile_fields_are_still_there(recorded: dict[str, Any]) -> None:
    """Keep the exclusion in :func:`stable` from quietly hiding a missing field.

    ``eta`` and the digests are left out of the comparison because they change every run. That
    makes them exactly the fields a future edit could drop without any test noticing, so they
    are asserted directly.

    ``eta`` is asserted only on a dispense, and that asymmetry is the design rather than an
    oversight: a held indent has no expected delivery time, and ``Run.public()`` omits the key
    instead of inventing one. A hold carrying an ETA would mean something had been dispatched.
    """
    for name, run in recorded["runs"].items():
        if run["status"] == "dispensed":
            assert re.fullmatch(r"\d{2}:\d{2}", run["eta"]), f"{name}: eta is not a wall clock"
            assert run["alert"]["eta"] == run["eta"], f"{name}: the phone and the record disagree"
        else:
            assert "eta" not in run, f"{name}: a held indent was given a delivery time"
            assert "alert" not in run, f"{name}: a held indent produced a notification"
        for event in run["audit"]:
            for key in ("hash", "prev_hash"):
                assert re.fullmatch(r"[0-9a-f]{64}", event[key]), (
                    f"{name}: {key} is not a digest"
                )


def test_the_recorded_chain_links(recorded: dict[str, Any]) -> None:
    """The page draws a chain, so the chain it draws has to be one.

    Tamper-evidence is the claim that section makes. Asserting the links here means the page
    cannot render a sequence of plausible-looking digests that do not actually connect.
    """
    for name, run in recorded["runs"].items():
        events = run["audit"]
        assert [event["sequence"] for event in events] == list(range(1, len(events) + 1)), (
            f"{name}: sequence numbers are not 1..n"
        )
        assert events[0]["prev_hash"] == "0" * 64, f"{name}: the chain does not start at genesis"
        for earlier, later in zip(events, events[1:]):
            assert later["prev_hash"] == earlier["hash"], f"{name}: the chain does not link"


def test_the_recorded_runs_carry_no_patient_data(recorded: dict[str, Any]) -> None:
    """The machine-generated half of the page is held to the same boundary as the wire.

    It is serialised into a file that gets opened, mailed around and committed. The claim that
    only the allowlist view may leave the process cannot stop at the HTTP response.
    """
    assert_no_phi(recorded)


#: NOTE — a gap, recorded here because this is where a reader would look for the test.
#:
#: The banner's sentence is *composed*: a lead clause, a colon, then ``run.detail``. Both
#: halves were individually correct and composed into a defect — ``detail`` is written
#: lowercase (it is also embedded in audit events) and the page appended it after a full stop,
#: so the one line a judge is meant to read began "…no phone was notified. prescribed 100
#: UNT/ML…". The same class of bug put a raw ``strength_mismatch`` in the banner's second line.
#:
#: Nothing in this suite can catch that. The bug exists only in the rendered sentence and this
#: suite does not run JavaScript; every string involved is individually correct, so no
#: assertion over the page's markup or the pipeline's output can see it. It was found by
#: executing the page's script against a stub DOM and reading what came out — see the note in
#: WRITEUP.md. A checked-in version of that harness would need Node in a Python project, which
#: is why it is not here; the honest position is that the rendered copy is verified by eye.


# -- the hand-written block -------------------------------------------------------------


def test_every_fixture_is_offered_by_the_page(page: str) -> None:
    """Every fixture the pipeline knows about needs a label, or it has no button."""
    for name in fixtures.FIXTURES:
        assert name in page, f"the page offers no indent for the {name!r} fixture"


def test_the_copy_labels_every_fixture(copy: dict[str, Any]) -> None:
    """The button list is driven by this block, so it has to be the whole set — both ways."""
    assert set(copy["fixtures"]) == set(fixtures.FIXTURES)


def test_the_copy_names_every_hold_code(copy: dict[str, Any]) -> None:
    """Every code in the closed set has a sentence, not just the ones the demo reaches.

    Checked against the enum rather than against the fixtures, so a code that is documented but
    not currently reachable still has to be explained, and a code invented in the page fails.
    """
    codes = {value for name, value in vars(HoldCode).items() if not name.startswith("_")}
    assert codes, "the enum read as empty — this test would pass on anything"
    assert set(copy["holds"]) == codes


# -- the page itself --------------------------------------------------------------------


def test_the_gate_column_names_the_real_allowlist(page: str) -> None:
    """The middle column is the page's central claim, so it is pinned to the type it cites.

    ``ALERT_FIELDS`` is derived from ``DispatchAlert``'s own field list, so renaming a field
    there renames it everywhere the boundary is enforced. The page names the four fields in
    markup the script then fills by key. If those two drift, the column renders four empty
    values and the page quietly stops demonstrating anything — so they are asserted equal
    rather than merely asserted to be four.
    """
    assert tuple(re.findall(r'data-field="([^"]+)"', page)) == ALERT_FIELDS


def test_the_script_reads_no_alert_field_that_cannot_cross(page: str) -> None:
    """A property read off ``alert`` that is not on the allowlist would render as undefined.

    The gate values are filled by key, so a typo here is not a crash — it is a blank where a
    value should be, on the one column whose job is to show that values do cross.
    """
    script = re.findall(r"<script>\n(.*?)\n</script>", page, re.DOTALL)[-1]
    props = set(re.findall(r"\ba\.([a-z_]+)", script)) | set(
        re.findall(r"alert\.([a-z_]+)", script)
    )
    assert props, "no alert property read — the regex or the script changed"
    assert props <= set(ALERT_FIELDS), f"the page reads fields that cannot cross: {props}"


def test_the_page_fetches_nothing_undocumented(page: str) -> None:
    """The page is static and same-origin; it must not reach anywhere else.

    A demo page that quietly called a third party would be a network egress the rest of this
    project is careful not to have, and it would be invisible in every other test.
    """
    fetched = set(re.findall(r'fetch\(\s*"([^"]+)"', page))
    assert fetched, "no fetch call found — the regex or the page changed"
    assert fetched <= {"/health", "/indent/demo/"}, (
        f"the page fetches something undocumented: {sorted(fetched)}"
    )


def test_the_page_loads_no_external_script(page: str) -> None:
    """It has to work from a filesystem path as well as from the server.

    The only external reference the page is allowed is the stylesheet's font, and that degrades
    to system fonts. A script with an ``src`` would not: a reviewer opening the file directly
    would get a page that looks finished and does nothing.
    """
    for tag in re.findall(r"<script[^>]*>", page):
        assert "src=" not in tag, f"the page loads a script it cannot guarantee: {tag}"
